### ISSUE TITLE
transaction not possible and mempool full. try again.

### ISSUE THREAD

**Issue by lukeorganic** [Berry-Pool/spacebudz#21]
I get transaction not possible when attempting to cancel my listing.

So I proceeded to delete coekies and browsing history and de-collateralize in Nami. This went fine

Then when trying to re-collateralize I got an error " mempool full, try again."

<img width="703" alt="image" src="https://user-images.githubusercontent.com/91955910/150578917-df40ab6c-c864-4c55-8ec7-b9d4e7d1768a.png">

<img width="295" alt="image" src="https://user-images.githubusercontent.com/91955910/150578949-ce922731-ded7-485a-b100-2f010e9c43f5.png">

**Comment by alessandrokonrad** [comment]
Hey things should run a littlbe bit better now. The chain is very congested right now. Let me know if you if you were able to make the transaction already.
