### ISSUE TITLE
Api example

### ISSUE THREAD

**Issue by naeri-kailash** [Berry-Pool/spacebudz#25]
Hey, thanks for opensourcing this, its awesome! I was wondering if you have some kind of framework available that you built the api for offers/bids etc on? Thanks

**Comment by alessandrokonrad** [comment]
Hey thank you!
Under the hood I'm using [Ogmios](https://ogmios.dev/) to retreive all the on-chain data. I haven't open sourced the SpaceBudz API yet, but could actually do that.

**Comment by naeri-kailash** [comment]
That would be really amazing if its not too much trouble @alessandrokonrad

**Comment by alessandrokonrad** [comment]
Hey I have it here now: https://github.com/Berry-Pool/spacebudz-api

**Comment by naeri-kailash** [comment]
Thank you @alessandrokonrad , really appreciate it! 🙌

**Comment by naeri-kailash** [comment]
Hey @alessandrokonrad , just revisiting this - 

From what I've gathered, in the `spacebudz-api` project you shared the program syncs with the cardano node, reads transactions relevant to the spacebudz project/given policy id and dumps the information into a db file. 

So I was wondering - did you have a separate project that serves `https://spacebudz.io/api/`? I'm guessing this api must read from the db that `spacebudz-api` dumps into and has the routes `/multisig/`, `/v2/common`, `/v2/spacebud/budId`, `/v2/listings` and `/v2/bids`. 

I hope my question makes sense, I feel like I must be missing something obvious! I was looking as trying to set up an api based off the api calls made from the marketplace but I'm not too sure what the multisig routes are doing. 

Thanks again :) Naeri
