### ISSUE TITLE
Can't resolve 'process/browser'

### ISSUE THREAD

**Issue by cherryrazzles** [Berry-Pool/spacebudz#31]
Hi! Thank you so much for making this an open resource. The new code looks amazing!

I was trying to compile and after adding the secrets page I got this error and I can't solve it on my own...

"
Module not found: Error: Can't resolve 'process/browser' in '/Users/myname/node_modules/safer-buffer'
    ModuleNotFoundError: Module not found: Error: Can't resolve 'process/browser' in '/Users/myname/node_modules/safer-b
  uffer'
"

I know it comes from gatsby-node.js, but I don't understand how I can make it work. 

Thank you

**Comment by alessandrokonrad** [comment]
Hey thank you!
What node.js version do you run?

**Comment by cherryrazzles** [comment]
I'm on the latest one 16.14.2
Do I need to downgrade it? Which node did you use?

**Comment by alessandrokonrad** [comment]
I'm running v14.18.2. You could try that.
