### ISSUE TITLE
Spacebudz api and how you serve it

### ISSUE THREAD

**Issue by naeri-kailash** [Berry-Pool/spacebudz#32]
Hey @alessandrokonrad , just revisiting the api query -

From what I've gathered, in the spacebudz-api project you shared the program syncs with the cardano node, reads transactions relevant to the spacebudz project/given policy id and dumps the information into a db file.

So I was wondering - did you have a separate project that serves https://spacebudz.io/api/? I'm guessing this api must read from the db that spacebudz-api dumps into and has the routes /multisig/, /v2/common, /v2/spacebud/budId, /v2/listings and /v2/bids.

I hope my question makes sense, I feel like I must be missing something obvious! I was looking as trying to set up an api based off the api calls made from the marketplace but I'm not too sure what the multisig routes are doing.

Thanks again :) Naeri

**Comment by alessandrokonrad** [comment]
Hey, yes exactly https://spacebudz.io/api/ is separate project. It's an API running on Firebase. I feed this APIs all the data coming from the open sourced spacebudz-api library.

> I hope my question makes sense, I feel like I must be missing something obvious! I was looking as trying to set up an api based off the api calls made from the marketplace but I'm not too sure what the multisig routes are doing.

Some of these routes relate to something else than the on-chain marketplace data. /multisig relates to our SpaceBudz multisig wallet.

**Comment by naeri-kailash** [comment]
Thanks that helps heaps :)
